# Global settings
title = "timergy"
version = "0.1"
description = "A library to manage and tidy up timeseries data."

# Author information
[author]
name = "Marco Virgili"
email = "marco.virgili15@gmail.com"

[dependencies]
pandas = "2.2"
DateTime = "5.5"
pytest = "8.3"